CREATE TABLE IF NOT EXISTS "posts" (
    id SERIAL NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    password VARCHAR(255) DEFAULT NULL,
    created TIMESTAMP NOT NULL DEFAULT NOW(),
    modified TIMESTAMP DEFAULT NULL,
    deleted TIMESTAMP DEFAULT NULL
);

